services:
  overseerr-bot:
    build: .
    container_name: overseerr-bot
    restart: unless-stopped
    env_file:
      - .env
    network_mode: host
    volumes:
      - ./data:/app/data
    environment:
      - USERS_FILE=/app/data/users.json
      - STATES_FILE=/app/data/states.json
